/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace AgreementRegistry {
  export type AgreementStruct = {
    agreementId: string;
    subscriber: AddressLike;
    provider: AddressLike;
    termsHash: string;
    isActive: boolean;
    createdAt: BigNumberish;
  };

  export type AgreementStructOutput = [
    agreementId: string,
    subscriber: string,
    provider: string,
    termsHash: string,
    isActive: boolean,
    createdAt: bigint
  ] & {
    agreementId: string;
    subscriber: string;
    provider: string;
    termsHash: string;
    isActive: boolean;
    createdAt: bigint;
  };
}

export interface AgreementRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agreementIds"
      | "agreements"
      | "getAgreement"
      | "registerAgreement"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "AgreementRegistered"): EventFragment;

  encodeFunctionData(
    functionFragment: "agreementIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "agreements", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getAgreement",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAgreement",
    values: [string, AddressLike, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "agreementIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "agreements", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAgreement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAgreement",
    data: BytesLike
  ): Result;
}

export namespace AgreementRegisteredEvent {
  export type InputTuple = [
    agreementId: string,
    subscriber: AddressLike,
    provider: AddressLike
  ];
  export type OutputTuple = [
    agreementId: string,
    subscriber: string,
    provider: string
  ];
  export interface OutputObject {
    agreementId: string;
    subscriber: string;
    provider: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgreementRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): AgreementRegistry;
  waitForDeployment(): Promise<this>;

  interface: AgreementRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agreementIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  agreements: TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, string, boolean, bigint] & {
        agreementId: string;
        subscriber: string;
        provider: string;
        termsHash: string;
        isActive: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  getAgreement: TypedContractMethod<
    [_agreementId: string],
    [AgreementRegistry.AgreementStructOutput],
    "view"
  >;

  registerAgreement: TypedContractMethod<
    [_agreementId: string, _provider: AddressLike, _termsHash: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agreementIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "agreements"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, string, boolean, bigint] & {
        agreementId: string;
        subscriber: string;
        provider: string;
        termsHash: string;
        isActive: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAgreement"
  ): TypedContractMethod<
    [_agreementId: string],
    [AgreementRegistry.AgreementStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerAgreement"
  ): TypedContractMethod<
    [_agreementId: string, _provider: AddressLike, _termsHash: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AgreementRegistered"
  ): TypedContractEvent<
    AgreementRegisteredEvent.InputTuple,
    AgreementRegisteredEvent.OutputTuple,
    AgreementRegisteredEvent.OutputObject
  >;

  filters: {
    "AgreementRegistered(string,address,address)": TypedContractEvent<
      AgreementRegisteredEvent.InputTuple,
      AgreementRegisteredEvent.OutputTuple,
      AgreementRegisteredEvent.OutputObject
    >;
    AgreementRegistered: TypedContractEvent<
      AgreementRegisteredEvent.InputTuple,
      AgreementRegisteredEvent.OutputTuple,
      AgreementRegisteredEvent.OutputObject
    >;
  };
}
